file_format: "1"
id: lily58
name: Lily58
type: shield
url: https://github.com/kata0510/Lily58
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - pointer
siblings:
  - lily58cirque_left
  - lily58cirque_right
