manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: miketronic
      url-base: https://github.com/miketronic/
    - name: halfdane
      url-base: https://github.com/halfdane/
    - name: johanson
      url-base: https://github.com/petejohanson
    - name: miryoku
      url-base: https://github.com/manna-harbour/
  projects:
    - name: zmk
      remote: johanson
      revision: split/wired-split-first-pass
      import: app/west.yml
    - name: zephyr
      remote: johanson
      revision: v3.5.0+zmk-fixes+rp2040-uart-fifo
      import: west.yml
#    - name: zmk
#      remote: halfdane
#      revision: rp2040zero
#      import: app/west.yml
    - name: cirque-input-module
      remote: halfdane
      revision: absolute_mode
    - name: zmk-input-processors
      remote: halfdane
      revision: main
    - name: zmk-input-gestures
      remote: halfdane
      revision: main
    - name: miryoku_zmk
      remote: halfdane
      revision: master
  self: 
    path: config

